apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;

      location /api/ {
        proxy_pass http://{{ .Values.backend.service.name | default "backend"}}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api/;
      }

      location /metrics {
        proxy_pass http://{{ .Values.backend.service.name | default "backend"}}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/metrics;
      }


      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
      }
    }
