apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name | default "backend" }}
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
  type: {{ .Values.backend.service.type }}
