apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name | default "frontend" }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      nodePort: {{ .Values.frontend.service.nodePort | default 30083 }}
  type: {{ .Values.frontend.service.type }}
  